### ISSUE TITLE
apiproduct-operations setup script fails

### ISSUE THREAD

**Issue by dfong** [GoogleCloudPlatform/apigee-samples#153]
**Describe the bug**

when i try to run the apiproduct-operations script setup-apiproduct-operations.sh, it always fails.  here is a partial output.

```
> apigee-sample-apiproduct-operations@1.0.0 test
> npx cucumber-js --publish-quiet test/

Environment variables [APIGEE_HOST, SAMPLE_PROXY_BASEPATH, VIEWER_CLIENT_ID, CREATOR_CLIENT_ID, ADMIN_CLIENT_ID, VIEWER_CLIENT_SECRET, CREATOR_CLIENT_SECRET, ADMIN_CLIENT_SECRET] must be set before the tests can be run.
Missing: [SAMPLE_PROXY_BASEPATH, VIEWER_CLIENT_ID, CREATOR_CLIENT_ID, ADMIN_CLIENT_ID, VIEWER_CLIENT_SECRET, CREATOR_CLIENT_SECRET, ADMIN_CLIENT_SECRET]

Please set the Environment variables and try running the command again.

Error: setup-apiproduct-operations.sh failed!
```

i think what's happening here is that the "setup-apiproduct-operations" script contains a mixture of "setup commands" and "test commands".  it looks like some of the test commands require the setting of environment variables whose values are printed by the "setup commands".  is it the intention that the user would read the output from the "setup commands" and then paste them into the current environment?  but since both the setup and test are being run from the one script, there is no opportunity for the user to do this.

assuming the above is correct, i think the cleanest solution would be to move the "test" commands into a separate script.

an alternative would be to automate the passing of environment variables, so the setup script can run without intervention.

it would also help if the README file had a description of the expected value of each and every environment variable.  currently SAMPLE_PROXY_BASEPATH is not explained.

**To Reproduce**

run setup-apiproduct-operations.sh

**Expected behavior**

the setup script should exit with status 0 and no error messages.

after this, i should be able to run the test script, with all tests passing.

after this, i should be able to run the cleanup script, and repeat.

**Comment by ssvaidyanathan** [comment]
@DinoChiesa - can you pls take a look?

**Comment by ssvaidyanathan** [comment]
Works as expected
