### ISSUE TITLE
deploy script for authorize-idp-access-tokens fails

### ISSUE THREAD

**Issue by dfong** [GoogleCloudPlatform/apigee-samples#155]
**Describe the bug**

when i run deploy-authorize-idp-access-tokens.sh, i get errors.  one of them (seemingly the first) is from sed.

```
Deploying Apigee artifacts...
sed: can't read ./rendered/sharedflowbundle/policies/VK-IdentifyClientApp.xml: No such file or directory
```

indeed the file is not there.  but, the file *VA*-IdentifyClientApp.xml does exist.  so it looks like a mismatch.

in addition, after this error (which should be fatal) the script keeps running, and produces further confusing errors.

generally, this script would benefit from better error handling.  for example, i would suggest adding "|| exit" to the sed command.

**To Reproduce**

run ./deploy-authorize-idp-access-tokens.sh .  examine the output.

**Expected behavior**

deploy should run with no errors, and exit with status 0.

**Additional context**

running on a cloudtop VM.  my org is in staging.

**Comment by ssvaidyanathan** [comment]
Fixed
