### ISSUE TITLE
apigeecli invalid flags used in deploy-authorize-idp-access-tokens.sh

### ISSUE THREAD

**Issue by dfong** [GoogleCloudPlatform/apigee-samples#156]
**Describe the bug**

when i run the deploy script, errors appear.  and the script keeps running regardless.

```
Importing and Deploying Apigee authorize-idp-access-tokens sharedflow...
+[4] command apigeecli sharedflows create -f ./rendered/sharedflowbundle -n authorize-idp-access-tokens --org djfong-autopush-ngsaas --token *****--disable-check --api=staging
Error: unknown shorthand flag: 'f' in -f
Usage:
  apigeecli sharedflows create [command]
```

**To Reproduce**

run ./deploy-authorize-idp-access-tokens.sh.

**Expected behavior**

the script should run with no errors, and exit with status 0.
or if an error does occur, the script should exit immediately with a nonzero status.

**Additional context**

running the sample on a cloudtop VM.  my org is in staging.

**Comment by ssvaidyanathan** [comment]
Fixed
