### ISSUE TITLE
the Cloud Run tutorial should mention how to associate a SA with an existing api proxy endpoint

### ISSUE THREAD

**Issue by saraford** [GoogleCloudPlatform/apigee-samples#49]
The tutorial on https://github.com/GoogleCloudPlatform/apigee-samples/blob/main/cloud-run/docs/cloudshell-tutorial-maven.md should include steps on how to 1) grant the Cloud Run invoker role to the SA 2) how to assign the SA within the API Proxy editor (e.g. when repeating these steps for an existing api proxy).  

It isn't clear from reading the cloudbuild.yaml file how you'd do this step for an existing endpoint. https://github.com/GoogleCloudPlatform/apigee-samples/blob/main/cloud-run/cloudbuild.yaml#L53-L54

**Comment by ssvaidyanathan** [comment]
@saraford - 

Its all automated as part of the Cloud Build itself.

The service account is created by the Cloud Build itself and it assigns the Cloud Run Invoker role too. You can find that on https://github.com/GoogleCloudPlatform/apigee-samples/blob/c92dedbead278ee23f6e7aa3f7e360eea8904f63/cloud-run/cloudbuild.yaml#L38 and https://github.com/GoogleCloudPlatform/apigee-samples/blob/c92dedbead278ee23f6e7aa3f7e360eea8904f63/cloud-run/cloudbuild.yaml#L40

**Comment by saraford** [comment]
fwiw, this was my first time using Cloud Run with Apigee. I thought in the future, if I wanted to use CR and Apigee without running this tutorial, I'd have to run that mvn command on line 53 myself somehow. I thought it was doing something else. I'm hoping the tutorial could be updated to mention that a new SA will be created with these permissions; otherwise, reverse-engineering the cloudbuild.yaml (like what I was trying to do) might lead to misinterpretations of what's needed.
